theme: jekyll-theme-primer
title: Xtreamer Remote
description: Xtreamer Remote / Remote for Xtreamer is a remote control android app for your Xtreamer Media Player.
github: 
  is_project_page: false
